---
- name: Install packages to Debian
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - git
    - apt-transport-https
    - nginx
  when: ansible_os_family == 'Debian'

- name: Install packages to RedHat
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - epel-release
    - git
    - nginx
    - yum-utils
    - http://rpms.remirepo.net/enterprise/remi-release-7.rpm
  when: ansible_os_family == 'RedHat'

- name: Check out master branch
  git:
    repo: 'https://github.com/monicahq/monica'
    dest: /srv/monicahq
    version: main

- name: Add the user
  user:
    name: monicahq
    shell: /usr/bin/nologin
    home: /srv/monicahq

- name: Install sury key to Debian
  apt_key:
    url: 'https://packages.sury.org/php/apt.gpg'
    state: present
  when: ansible_os_family == 'Debian'

- name: Add sury repositories to Debian
  apt_repository:
    repo: "deb https://packages.sury.org/php/ stretch main"
    state: present
    update_cache: yes
    filename: 'sury'
  when: ansible_os_family == 'Debian'

- name: install php dependencies to Debian
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - php7.3
    - php7.3-cli
    - php7.3-intl
    - php7.3-iconv
    - php7.3-fpm
    - php7.3-curl
    - php7.3-gd
    - php7.3-mysql
    - php7.3-mysqli
    - php7.3-opcache
    - php7.3-json
    - php7.3-mbstring
    - php7.3-soap
    - php7.3-xml
    - php7.3-zip
    - php7.3-gmp
    - php7.3-bcmath
    - php-memcached
    - php-xdebug
    - php-redis
  when: ansible_os_family == 'Debian'

- name: Enable PHP 8.1 repo to Redhat
  shell: "yum-config-manager --enable remi-php81"
  when: ansible_os_family == 'RedHat'

- name: install php dependencies to RedHat
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - php
    - php-cli
    - php-intl
    - php-iconv
    - php-fpm
    - php-curl
    - php-gd
    - php-mysql
    - php-mysqli
    - php-opcache
    - php-json
    - php-mbstring
    - php-soap
    - php-xml
    - php-zip
    - php-gmp
    - php-bcmath
    - php-memcache
    - php-pecl-xdebug
    - php-pecl-redis
  when: ansible_os_family == 'RedHat'

- name: Reload service php-fcgi
  become: true
  systemd:
    name: php73-php-fpm
    state: reloaded
  when: ansible_os_family == 'Debian'

- name: Reload service php-fcgi
  become: true
  systemd:
    name: php-fpm
    state: reloaded
  when: ansible_os_family == 'RedHat'

- name: Install composer
  include_role:
    name: geerlingguy.composer

- name: Install composer dependencies
  composer:
    command: install
    working_dir: /srv/monicahq

- name: Prepare configuration
  template:
    src: env.j2
    dest: /srv/monicahq/.env

- name: Run an initial key generation
  command: "/usr/bin/php /srv/monicahq/artisan key:generate"
  args:
    chdir: /srv/monicahq/
  tags: molecule-notest

- name: Run an initial migration
  command: "/usr/bin/php /srv/monicahq/artisan setup:production --force"
  args:
    chdir: /srv/monicahq/
  tags: molecule-notest

- name: Place a scheduler cron job
  cron:
    user: monicahq
    name: "scheduler"
    job: "/usr/bin/php /srv/monicahq/artisan schedule:run"

- name: Recursively change ownership of a directory
  file:
    path: /srv/monicahq
    state: directory
    recurse: yes
    owner: monicahq
    group: www-data

- name: Put right permissions to storage
  file:
    path: /srv/monicahq/storage
    state: directory
    recurse: yes
    mode: g+w

- name: Create nginx vhost config
  template:
    src: monicahq.conf.j2
    dest: /etc/nginx/sites-enabled/monica.conf

- name: Remove default nginx configuration
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Reload service nginx
  become: true
  systemd:
    name: nginx
    state: reloaded
